<template>
  <div v-document-title="`Imprint & Data Privacy`" v-meta-description="">
    <h1 class="md-headline">Imprint & Data Privacy</h1>

    <p>
      <strong>Manuel Wieser</strong><br>
      <a href="mailto:office@manuelwieser.com">office@manuelwieser.com</a><br>
      Weingartshofstraße 29<br>
      4020 Linz<br>
      AUSTRIA
    </p>

    <h2 class="md-title">Cookies</h2>
    <div>
      <p>
        This website uses third-party cookies, which are stored by
        providers other than the person who manages this website.
      </p>
      <p>
        If you do not want cookies to be stored on your computer, please
        disable them in your browser’s settings. Saved cookies can also
        be deleted in the settings of the browser. The exclusion of
        cookies can lead to functional restrictions of this website.
      </p>
    </div>

    <h2 class="md-title">Hosting</h2>
    <div>
      <p>
        This website, or rather its hosting provider, logs every access
        to the server on which this service is located. The access data
        includes the name of the requested web page or file, date and
        time of retrieval, amount of data transferred, information about
        successful retrieval, browser type and version, the user’s
        operating system, referrer URL (the previously visited page), IP
        address and the requesting provider.
      </p>
      <p>
        This website is hosted by Netlify. For more information about
        Netlify’s data usage, please read
        <a href="https://www.netlify.com/privacy/">
          Netlify’s Privacy Policy
        </a>.
      </p>
    </div>

    <h2 class="md-title">Google Analytics</h2>
    <div>
      <p>
        This website uses Google Analytics, a web analytics service
        provided by Google.
        <a href="https://www.privacyshield.gov/participant?id=a2zt000000001L5AAI&status=Active">
          Google is certified under the Privacy Shield Agreement
        </a>, which provides a guarantee to comply with European privacy
        legislation.
      </p>
      <p>
        Information generated by
        <a href="https://developers.google.com/analytics/devguides/collection/analyticsjs/cookie-usage">
          Google Analytics’s cookies
        </a> about the user’s website usage is usually transmitted to a
        Google server in the USA and stored there.
      </p>
      <p>
        Google uses this information on this website's behalf to
        evaluate the use of the website by users, to compile reports on
        the activities within this website and to provide further
        services related to the use of this website and the internet
        usage. In this case, pseudonymous usage profiles of the users
        can be created from the processed data.
      </p>
      <p>
        This website only uses Google Analytics with activated IP
        anonymization. This means that the IP address of the users will
        be shortened by Google within member states of the European
        Union or in other contracting states of the Agreement on the
        European Economic Area. Only in exceptional cases will the full
        IP address be sent to a Google server in the US and shortened
        there.
      </p>
      <p>
        The IP address submitted by the user’s browser will not be
        merged with other data provided by Google. Users can prevent the
        storage of cookies by changing their browser settings. Users may
        also prevent the collection by Google of the data generated by
        the cookie and related to its use of the website and the
        processing of such data by Google by downloading and installing a
        <a href="https://tools.google.com/dlpage/gaoptout">
          browser-plugin
        </a>.
      </p>
      <p>
        For more information about Google’s data usage, please read
        <a href="https://policies.google.com/technologies/ads">
          Google’s Privacy Policy
        </a>
        and
        <a href="https://adssettings.google.com/authenticated">
          Google’s Ads Settings
        </a>.
      </p>
    </div>
  </div>
</template>
